[workspace]
members = [ "day1", "day2", "day3", "day4", "day5", "day6","libutils"]
resolver = "2"

[workspace.dependencies]
libutils = { version = "0.1.0", path = "./libutils" }
thiserror = "2.0.3"
regex = "1.11.1"
